#include <assert.h>
#include <stdio.h>
#include <string.h>

const char *filelist = "img/filelist.txt";
const char *tmplate =
    "<!DOCTYPE html5>"
    "<html lang=\"en\">"
    "  <head>"
    "    <meta charset=\"utf-8\" />"
    "    <title>Hell</title>"
    "    <link href=\"../css/common.css\" rel=\"stylesheet\" />"
    "    <link href=\"../css/rotate.css\" rel=\"stylesheet\" />"
    "  </head>"
    "  <style>"
    "    .container {"
    "      width: 50%%;"
    "      margin: auto;"
    "      margin-top: 4%%;"
    "      padding: 5%%;"
    "      padding-top: 2%%;"
    "      border: 0;"
    "      border-radius: 10px;"
    "      background-color: #00000060;"
    "    }"
    ""
    "    .text {"
    "      margin-top: 0px;"
    "      color: aliceblue;"
    "      font-family: \"Gill Sans\", \"Gill Sans MT\", Calibri, \"Trebuchet "
    "MS\","
    "        sans-serif;"
    "    }"
    ""
    "    .wrapper {"
    "      width: 100%%;"
    "      overflow: hidden;"
    "    }"
    ""
    "    img,"
    "    canvas {"
    "      max-width: 100%%;"
    "    }"
    ""
    "    button {"
    "      display: inline-block;"
    "      margin: 15px;"
    "      margin-left: 0px;"
    "      padding: 10px;"
    "      background-color: #00000060;"
    "      text-align: center;"
    "      font-size: 20px;"
    "      font-weight: 500;"
    "      color: aliceblue;"
    "      border-radius: 15px;"
    "      font-family: \"Courier New\", Courier, monospace;"
    "    }"
    ""
    "    .range {"
    "      margin: 15px;"
    "      margin-left: 0px;"
    "      margin-top: 0px;"
    "    }"
    ""
    "    .range input {"
    "      display: block;"
    "      width: 100%%;"
    "      margin: 15px;"
    "      margin-left: 0px;"
    "      height: 8px;"
    "      border-radius: 4px;"
    "    }"
    ""
    "    .col {"
    "      float: left;"
    "    }"
    ""
    "    .col2 {"
    "      width: 45%%;"
    "    }"
    "  </style>"
    "  <body>"
    "    <header>"
    "      <div class=\"title\">Hell</div>"
    "      <a class=\"button\" href=\"../index.html\">home</a>"
    "      <a class=\"button\" href=\"../register.html\">sign up</a>"
    "      <a class=\"button\" href=\"../login.html\">sign in</a>"
    "    </header>"
    ""
    "    <div class=\"container\">"
    "      <h2 class=\"text\">origin image</h2>"
    "      <div class=\"wrapper\">"
    "        <img class=\"rotate\" id=\"img\""
    "        src=\"%s\""
    "alt=\"Picture\"/>"
    "      </div>"
    "      <button id=\"rotate\">rotate 180</button>"
    "      <div class=\"range\" id=\"brightness\">"
    "        <h3 class=\"text\">brightness: <span>1</span></h3>"
    "        <input type=\"range\" value=\"1\" min=\"0\" max=\"2\" "
    "step=\"0.01\" />"
    "      </div>"
    "      <div class=\"range\" id=\"opacity\">"
    "        <h3 class=\"text\">opacity: <span>1</span></h3>"
    "        <input type=\"range\" value=\"1\" min=\"0\" max=\"1\" "
    "step=\"0.01\" />"
    "      </div>"
    "      <div class=\"range\" id=\"saturate\">"
    "        <h3 class=\"text\">saturate: <span>1</span></h3>"
    "        <input type=\"range\" value=\"1\" min=\"0\" max=\"2\" "
    "step=\"0.01\" />"
    "      </div>"
    "      <div class=\"range\" id=\"invert\">"
    "        <h3 class=\"text\">invert: <span>0</span></h3>"
    "        <input type=\"range\" value=\"0\" min=\"0\" max=\"1\" "
    "step=\"0.01\" />"
    "      </div>"
    "      <div class=\"range\" id=\"contrast\">"
    "        <h3 class=\"text\">contrast: <span>1</span></h3>"
    "        <input type=\"range\" value=\"1\" min=\"0\" max=\"2\" "
    "step=\"0.01\" />"
    "      </div>"
    "      <div class=\"range\" id=\"grayscale\">"
    "        <h3 class=\"text\">grayscale: <span>0</span></h3>"
    "        <input type=\"range\" value=\"0\" min=\"0\" max=\"1\" "
    "step=\"0.01\" />"
    "      </div>"
    "      <div class=\"range\" id=\"sepia\">"
    "        <h3 class=\"text\">sepia: <span>0</span></h3>"
    "        <input type=\"range\" value=\"0\" min=\"0\" max=\"1\" "
    "step=\"0.01\" />"
    "      </div>"
    "      <h2 class=\"text\">preset filters</h2>"
    "      <h3 class=\"text\">it is very slow... plz be patient.</h3>"
    "      <div class=\"wrapper col\">"
    "        <img class=\"col2\" id=\"preset\""
    "        src=\"%s\""
    "alt=\"Picture\"/>"
    "        <canvas class=\"col2\" id=\"canvas\"></canvas>"
    "      </div>"
    "      <button id=\"vintage\">vintage</button>"
    "      <button id=\"lomo\">lomo</button>"
    "      <button id=\"clarity\">clarity</button>"
    "      <button id=\"sunrise\">sunrise</button>"
    "      <button id=\"love\">love</button>"
    "      <h2 class=\"text\">cropper</h2>"
    "      <div class=\"wrapper\">"
    "        <img id=\"crop-img\""
    "        src=\"%s\""
    "alt=\"Picture\"/>"
    "      </div>"
    "      <button id=\"crop-btn\">crop</button>"
    "      <h2 class=\"text\">cropped image</h2>"
    "      <div id=\"crop-res\"></div>"
    "    </div>"
    ""
    "    <link"
    "      rel=\"stylesheet\""
    "      "
    "href=\"https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.12/"
    "cropper.css\""
    "    />"
    "    <script "
    "src=\"https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.12/"
    "cropper.min.js\"></script>"
    "    <script "
    "src=\"https://cdnjs.cloudflare.com/ajax/libs/camanjs/4.1.2/"
    "caman.full.min.js\"></script>"
    "    <script src=\"../js/crop.js\"></script>"
    "    <script src=\"../js/rotate.js\"></script>"
    "    <script src=\"../js/common.js\"></script>"
    "    <script>"
    "let presets = [\"vintage\", \"lomo\", \"clarity\", \"sunrise\", "
    "\"love\"];"
    ""
    "      presets.forEach((cur) => {"
    "        let btn = document.getElementById(cur);"
    "        btn.addEventListener(\"click\", () => {"
    "          Caman(\"#canvas\","
    "\"%s\","
    "function () {"
    "            if (cur.startsWith(\"vintage\")) {"
    "              this.vintage();"
    "            }"
    "            if (cur.startsWith(\"lomo\")) {"
    "              this.lomo();"
    "            }"
    "            if (cur.startsWith(\"clarity\")) {"
    "              this.clarity();"
    "            }"
    "            if (cur.startsWith(\"sunrise\")) {"
    "              this.sunrise();"
    "            }"
    "            if (cur.startsWith(\"love\")) {"
    "              this.love();"
    "            }"
    "            this.render();"
    "          });"
    "        });"
    "      });"
    "    </script>"
    "  </body>"
    "</html>"
    "";

static void cfile(char *img, int c) {
  char cstr[5] = {0};
  sprintf(cstr, "%d", c);
  // html name
  char name[64] = "imgw/imgw";
  strcat(name, cstr);
  strcat(name, ".html");
  name[strlen(name)] = 0;
  // code
  char code[strlen(tmplate) + 640];
  memset(code, 0, strlen(tmplate) + 640);
  sprintf(code, tmplate, img, img, img, img);
  // generate
  printf("%s\n", name);
  FILE *fp = fopen(name, "w");
  assert(fp != NULL);
  fputs(code, fp);
  fclose(fp);
}

int main() {
  FILE *fp = fopen(filelist, "r");
  assert(fp != NULL);

  char tmp[1024];
  int count = 0;
  while (fgets(tmp, 1024, fp) != NULL) {
    ++count;
    if (tmp[strlen(tmp) - 1] == '\n')
      tmp[strlen(tmp) - 1] = 0;
    cfile(tmp, count);
    memset(tmp, 0, 1024);
  }
  fclose(fp);
}